/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vue;
import Controleur.Connexion;
import java.sql.*;
import vue.Recherche;
/**
 *
 * @author axel9
 */
public class Rch_Patients extends javax.swing.JFrame {
    private static Connexion link;
    /** Creates new form Rch_Patients */
    public Rch_Patients(Connexion l) {
        initComponents();
        link=l;
 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Retour = new javax.swing.JButton();
        Texte_recherche = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Categorie = new javax.swing.JComboBox<>();
        Attribut = new javax.swing.JComboBox<>();
        Recherche = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Retour.setText("Retour");
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });

        Texte_recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Texte_rechercheActionPerformed(evt);
            }
        });

        jLabel1.setText("Rechercher par :");

        Categorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hospitalisé", "Tout" }));
        Categorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategorieActionPerformed(evt);
            }
        });

        Attribut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aucun", "numero", "nom", "prenom", "adresse", "tel", "mutuelle", "no_doc", "nom_doc", "prenom_doc", "tel_doc", "specialite" }));

        Recherche.setText("Recherche");
        Recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercheActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "numero", "nom", "prenom", "adresse", "tel", "mutuelle", "no_doc", "nom_doc", "prenom_doc", "tel_doc", "specialite"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Retour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 728, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Categorie, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Attribut, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Texte_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Retour)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Texte_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Categorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Attribut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Recherche)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        Recherche Page_recherche= new Recherche(link);
        Page_recherche.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RetourActionPerformed

    private void Texte_rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Texte_rechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Texte_rechercheActionPerformed

    private void CategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategorieActionPerformed
        if(Categorie.getSelectedIndex()==0){
            if(Attribut.getItemCount()>12){
               Attribut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aucun", "numero", "nom", "prenom", "adresse", "tel", "mutuelle", "no_doc", "nom_doc", "prenom_doc", "tel_doc", "specialite" }));
               Attribut.addItem("no_chambre");
               Attribut.addItem("service");
               jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null,null,null},
                {null, null, null, null, null, null, null, null, null, null, null,null,null},
                {null, null, null, null, null, null, null, null, null, null, null,null,null},
                {null, null, null, null, null, null, null, null, null, null, null,null,null}
            },
            new String [] {
                "numero", "nom", "prenom", "adresse", "tel", "mutuelle", "no_doc", "nom_doc", "prenom_doc", "tel_doc", "specialite","no_chambre","service"
            }
        ));
            }
            else{
                 Attribut.addItem("no_chambre");
                 Attribut.addItem("service");
                 jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null,null,null},
                {null, null, null, null, null, null, null, null, null, null, null,null,null},
                {null, null, null, null, null, null, null, null, null, null, null,null,null},
                {null, null, null, null, null, null, null, null, null, null, null,null,null}
            },
            new String [] {
                "numero", "nom", "prenom", "adresse", "tel", "mutuelle", "no_doc", "nom_doc", "prenom_doc", "tel_doc", "specialite","no_chambre","service"
            }
        ));
            }      
        }
        if(Categorie.getSelectedIndex()==1){
            Attribut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aucun", "numero", "nom", "prenom", "adresse", "tel", "mutuelle", "no_doc", "nom_doc", "prenom_doc", "tel_doc", "specialite" }));
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "numero", "nom", "prenom", "adresse", "tel", "mutuelle", "no_doc", "nom_doc", "prenom_doc", "tel_doc", "specialite"
            }
        ));
        }
    }//GEN-LAST:event_CategorieActionPerformed

    private void RechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercheActionPerformed
        String SQL_P_H="SELECT DISTINCT M.numero, M.nom, M.prenom,M.adresse, M.tel,M.mutuelle, H.no_chambre, SV.nom as service ,E.numero as no_doc, E.nom as nom_doc, E.prenom as prenom_doc, E.tel as tel_doc, D.specialite FROM malade M,hospitalisation H,service SV, soigne S, docteur D, employe E WHERE M.numero=H.no_malade AND H.no_malade=S.no_malade AND S.no_docteur=D.numero AND D.numero=E.numero ";
        String SQL_P="SELECT DISTINCT M.numero, M.nom, M.prenom,M.adresse, M.tel,M.mutuelle,E.numero as no_doc, E.nom as nom_doc, E.prenom as prenom_doc, E.tel as tel_doc, D.specialite FROM malade M,service SV, soigne S, docteur D, employe E WHERE M.numero=S.no_malade AND S.no_docteur=D.numero AND D.numero=E.numero ";

        int C;
        C=Categorie.getSelectedIndex();
        int No_A;
        String SQL;
        switch(C){
    
                 case 0: 
                    No_A=Attribut.getSelectedIndex();
                     switch(No_A){
                    case 0:
                        SQL=SQL_P_H;
                        break;
                    case 1:
                        SQL=SQL_P_H+"WHERE numero like"+"'%"+Texte_recherche.getText()+"%'"+";";
                        break;
                    case 2:
                        SQL=SQL_P_H+"WHERE nom like"+"'%"+Texte_recherche.getText()+"%'"+";";
                        break;
                    case 3:
                        SQL=SQL_P_H+"WHERE prenom like"+"'%"+Texte_recherche.getText()+"%'"+";";
                        break;
                    case 4:
                        SQL=SQL_P_H+"WHERE adresse like"+"'%"+Texte_recherche.getText()+"%'"+";";
                        break;
                    case 5:
                        SQL=SQL_P_H+"WHERE tel like"+"'%"+Texte_recherche.getText()+"%'"+";";
                        break;
                    case 6:
                        SQL=SQL_P_H+"WHERE mutuelle like"+"'%"+Texte_recherche.getText()+"%'"+";";
                        break;
                    case 7:
                        SQL=SQL_P_H+"WHERE no_doc like"+"'%"+Texte_recherche.getText()+"%'"+";";
                        break;
                    case 8:
                        SQL=SQL_P_H+"WHERE nom_doc like"+"'%"+Texte_recherche.getText()+"%'"+";";
                        break;
                    case 9:
                        SQL=SQL_P_H+"WHERE prenom_doc like"+"'%"+Texte_recherche.getText()+"%'"+";";
                        break;
                    case 10:
                        SQL=SQL_P_H+"WHERE tel_doc like"+"'%"+Texte_recherche.getText()+"%'"+";";
                        break;
                    case 11:
                        SQL=SQL_P_H+"WHERE specialite like"+"'%"+Texte_recherche.getText()+"%'"+";";
                        break;
                    case 12:
                        SQL=SQL_P_H+"WHERE no_chambre like"+"'%"+Texte_recherche.getText()+"%'"+";";
                        break;
                    case 13:
                        SQL=SQL_P_H+"WHERE service like"+"'%"+Texte_recherche.getText()+"%'"+";";
                        break;
                    }
                    break;
            case 1: 
                No_A=Attribut.getSelectedIndex();
                switch(No_A){
                    case 0:
                        SQL=SQL_P;
                        break;
                    case 1:
                        SQL=SQL_P+"WHERE numero like"+"'%"+Texte_recherche.getText()+"%'"+";";
                        break;
                    case 2:
                        SQL=SQL_P+"WHERE nom like"+"'%"+Texte_recherche.getText()+"%'"+";";
                        break;
                    case 3:
                        SQL=SQL_P+"WHERE prenom like"+"'%"+Texte_recherche.getText()+"%'"+";";
                        break;
                    case 4:
                        SQL=SQL_P+"WHERE adresse like"+"'%"+Texte_recherche.getText()+"%'"+";";
                        break;
                    case 5:
                        SQL=SQL_P+"WHERE tel like"+"'%"+Texte_recherche.getText()+"%'"+";";
                        break;
                    case 6:
                        SQL=SQL_P+"WHERE mutuelle like"+"'%"+Texte_recherche.getText()+"%'"+";";
                        break;
                    case 7:
                        SQL=SQL_P+"WHERE no_doc like"+"'%"+Texte_recherche.getText()+"%'"+";";
                        break;
                    case 8:
                        SQL=SQL_P+"WHERE nom_doc like"+"'%"+Texte_recherche.getText()+"%'"+";";
                        break;
                    case 9:
                        SQL=SQL_P+"WHERE prenom_doc like"+"'%"+Texte_recherche.getText()+"%'"+";";
                        break;
                    case 10:
                        SQL=SQL_P+"WHERE tel_doc like"+"'%"+Texte_recherche.getText()+"%'"+";";
                        break;
                    case 11:
                        SQL=SQL_P+"WHERE specialite like"+"'%"+Texte_recherche.getText()+"%'"+";";
                        break;
                }
            }
        ///////////////////////////////////////////INTERROGATION DE LA BD/////////////////////////////////
       
        
        
        
    }//GEN-LAST:event_RechercheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rch_Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rch_Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rch_Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rch_Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rch_Patients(link).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Attribut;
    private javax.swing.JComboBox<String> Categorie;
    private javax.swing.JButton Recherche;
    private javax.swing.JButton Retour;
    private javax.swing.JTextField Texte_recherche;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
