/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;
import Controleur.Connexion;

/**
 *
 * @author Mathieu
 */
public class Maj_Employe extends javax.swing.JFrame {
    private static Connexion link;
    /**
     * Creates new form Maj_Employe
     */
    public Maj_Employe(Connexion l) {
        initComponents();
        link=l;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Retour_MAJ = new javax.swing.JButton();
        MAJ_docteur = new javax.swing.JButton();
        MAJ_infirmier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Retour_MAJ.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Retour_MAJ.setText("Retour");
        Retour_MAJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Retour_MAJActionPerformed(evt);
            }
        });

        MAJ_docteur.setText("MAJ docteur");
        MAJ_docteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAJ_docteurActionPerformed(evt);
            }
        });

        MAJ_infirmier.setText("MAJ infirmier");
        MAJ_infirmier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAJ_infirmierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Retour_MAJ))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(MAJ_docteur)
                        .addGap(30, 30, 30)
                        .addComponent(MAJ_infirmier)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Retour_MAJ)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MAJ_docteur)
                    .addComponent(MAJ_infirmier))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Retour_MAJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Retour_MAJActionPerformed
        // TODO add your handling code here:
        Mise_A_Jour MAJ=new  Mise_A_Jour(link);
        MAJ.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Retour_MAJActionPerformed

    private void MAJ_docteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAJ_docteurActionPerformed
        // TODO add your handling code here:
        Maj_docteur maj_docteur=new Maj_docteur(link);
        maj_docteur.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MAJ_docteurActionPerformed

    private void MAJ_infirmierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAJ_infirmierActionPerformed
        // TODO add your handling code here:
        Maj_infirmier maj_infirmier=new  Maj_infirmier(link);
        maj_infirmier.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MAJ_infirmierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maj_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maj_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maj_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maj_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maj_Employe(link).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MAJ_docteur;
    private javax.swing.JButton MAJ_infirmier;
    private javax.swing.JButton Retour_MAJ;
    // End of variables declaration//GEN-END:variables
}
