/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;
import Controleur.Connexion;
import Modele.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author ludovic
 */
public class Maj_P extends javax.swing.JFrame {
    private static Connexion link;
    /**
     * Creates new form Maj_PH
     */
    public Maj_P(Connexion l) {
        initComponents();
        link=l;
        AffichePatient();
    }
    /**
     * 
     * @return une ligne de la JTable
     */
    public ArrayList<Malade> getMaladeList(){
        ArrayList<Malade> list=new ArrayList<>();
        String query="SELECT DISTINCT M.numero, M.nom, M.prenom,M.adresse, M.mutuelle, M.tel,E.numero as num_doc, E.nom as nom_doc, E.prenom as prenom_doc, E.tel as tel_doc, D.specialite FROM malade M,hospitalisation H,soigne S ,docteur D, employe E WHERE M.numero=S.no_malade AND S.no_docteur=E.numero AND S.no_docteur=D.numero ORDER BY `M`.`numero` ASC";
        Statement st;
        ResultSet rs;
        try{
            st=link.getConn().createStatement();
            rs = st.executeQuery(query); 
            Malade malade;
            while(rs.next()){
                malade=new Malade(rs.getString("numero" ),rs.getString("nom"),rs.getString("prenom"),rs.getString("adresse"),rs.getString("tel"),rs.getString("mutuelle"),rs.getString("num_doc"),rs.getString("nom_doc"),rs.getString("prenom_doc"),rs.getString("tel_doc"),rs.getString("specialite"));
                list.add(malade);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return list;
    }
    /**
     * affiche les patients dans la Jtable
     */
    public void AffichePatient(){
        
        ArrayList<Malade> list = getMaladeList();
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        Object[] row = new Object[11];
        for(int i = 0; i < list.size(); i++) {
           row[0]=list.get(i).getNumero();
           row[1]=list.get(i).getNom();
           row[2]=list.get(i).getPrenom();
           row[3]=list.get(i).getAdresse();
           row[4]=list.get(i).getTel();
           row[5]=list.get(i).getMutuelle();
           row[6]=list.get(i).getNumDoc();
           row[7]=list.get(i).getNomDoc();
           row[8]=list.get(i).getPrenomDoc();
           row[9]=list.get(i).getTel();
           row[10]=list.get(i).getSpecialite();
           model.addRow(row);
       }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Retour = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idpat = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        adresse = new javax.swing.JTextField();
        mutuelle = new javax.swing.JTextField();
        num_doc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        Supprimer = new javax.swing.JButton();
        Modifier = new javax.swing.JButton();
        Ajouter = new javax.swing.JButton();
        tel = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Retour.setText("Retour");
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Mise à jour des patients");

        jLabel2.setText("Id patient");

        jLabel3.setText("Nom");

        jLabel4.setText("Prénom");

        jLabel5.setText("Adresse");

        jLabel6.setText("Mutuelle");

        jLabel7.setText("Id docteur");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "numero", "nom", "prenom", "adresse", "tel", "mutuelle", "num_doc", "nom_doc", "prenom_doc", "tel_doc", "specialite"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        Supprimer.setText("Supprimer");
        Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerActionPerformed(evt);
            }
        });

        Modifier.setText("Modifier");
        Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierActionPerformed(evt);
            }
        });

        Ajouter.setText("Ajouter");
        Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterActionPerformed(evt);
            }
        });

        jLabel12.setText("Téléphone");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Retour)
                        .addGap(200, 200, 200)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Ajouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Modifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Supprimer))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6))
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(adresse, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mutuelle, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(num_doc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prenom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idpat))
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)))
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Retour)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(idpat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mutuelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num_doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(150, 150, 150))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Supprimer)
                    .addComponent(Modifier)
                    .addComponent(Ajouter))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * 
     * @param evt retour à la page précédente
     */
    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        Mise_A_Jour maj=new Mise_A_Jour(link);
        maj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RetourActionPerformed
    /**
     * 
     * @param num numéro d'id du patient
     * @return true si le malade existe dans la bdd/fase autrement
     * @throws SQLException 
     */
    public boolean MaladeExiste(String num) throws SQLException{
        String query="SELECT numero FROM malade WHERE numero="+num;
        
        link.requetes=link.remplirChampsRequete(query);
        
        if(link.requetes.isEmpty())return false;//le malade n'est pas présent dans la bdd
        else return true;
    }
    /**
     * 
     * @param num id du docteur
     * @return vrai si le doc existe
     * @throws SQLException 
     */
    public boolean DocExiste(String num) throws SQLException{
        String query="SELECT numero FROM docteur WHERE numero="+num;
   
        link.requetes=link.remplirChampsRequete(query);
        
        if(link.requetes.isEmpty())return false;//le doc n'est pas présent dans la bdd
        else return true;
    }
    /**
     *  ajoute dans les table soigne,malade(au besoin) 
     * @param evt bouton ajouter pressé
     */
    private void AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterActionPerformed
        String query1,query3;
        
        if(idpat.getText().equals("")||nom.getText().equals("")||prenom.getText().equals("")
                ||adresse.getText().equals("")||tel.getText().equals("")||mutuelle.getText().equals("")||
                num_doc.getText().equals("")){
            JOptionPane.showMessageDialog(null,"L'un des champs est vide");
        }else{
            try {
                //vérif malade existant
                if(MaladeExiste(idpat.getText())){
                    JOptionPane.showMessageDialog(null,"Le malade est déjà présent dans la base");
                }else{
                    query3="INSERT INTO malade(numero,nom,prenom,adresse,tel,mutuelle) "
                            + "VALUES("+idpat.getText()+",'"+nom.getText()+"','"
                            +prenom.getText()+"','"+adresse.getText()+"','"+tel.getText()+"','"+mutuelle.getText()+"')";
                    executerSQLquery(query3,"Ajouté dans la table malade");
                }
                query1="INSERT INTO soigne(no_docteur,no_malade) VALUES ("+idpat.getText()+","+num_doc.getText()+");"; 
                executerSQLquery(query1,"Ajouté dans la table soigne");
               
                
            } catch (SQLException ex) {
                Logger.getLogger(Maj_PH.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_AjouterActionPerformed
    /**
     * modifie la table malade
     * @param evt modifier préssé
     */
    private void ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierActionPerformed
       //vérifier les champs 
        String query1,query2,query3;
        ArrayList<Object> lit,doc;
        if(idpat.getText().equals("")||nom.getText().equals("")||prenom.getText().equals("")
                ||adresse.getText().equals("")||tel.getText().equals("")||mutuelle.getText().equals("")||
                num_doc.getText().equals("")){
            JOptionPane.showMessageDialog(null,"L'un des champs est vide");
        }else{
            try {
                if(MaladeExiste(idpat.getText())){//vérif malade existant
                    //soigne ne peut pas être modifié car elle contient deux attributs primaire
                
                    query3="UPDATE malade SET `nom`='"+nom.getText()+"',`prenom`='"+prenom.getText()+"',`adresse`='"+adresse.getText()+"',`tel`='"+tel.getText()+"',mutuelle='"+mutuelle.getText()+"' WHERE `numero`="+idpat.getText()+";";
                    executerSQLquery(query3,"Table malade modifiée");
                }else{//modif
                JOptionPane.showMessageDialog(null,"Ce malade ou ce docteur n'éxiste pas");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Maj_PH.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ModifierActionPerformed
    /**
     * supprime le malade de toutes les bases existantes
     * @param evt "supprimer" à été enclenché
     */
    private void SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerActionPerformed
        //vérifier les champs 
        String query1,query2;
        ArrayList<Object> mal,doc;
        
        if(idpat.getText().equals("")||nom.getText().equals("")||prenom.getText().equals("")
                ||adresse.getText().equals("")||tel.getText().equals("")||mutuelle.getText().equals("")||
                num_doc.getText().equals("")){
            JOptionPane.showMessageDialog(null,"L'un des champs est vide");
        }else{
            try {
                if(MaladeExiste(idpat.getText())&&DocExiste(num_doc.getText())){//vérif malade&doc existant
                    //soigne ne peut pas être modifié car elle contien deux attributs primaire
                 
                    mal=link.remplirChampsRequete("SELECT no_malade FROM soigne WHERE no_malade="+idpat.getText()+" AND no_docteur="+num_doc.getText()+";");
                    doc=link.remplirChampsRequete("SELECT no_docteur FROM soigne WHERE no_malade="+idpat.getText()+" AND no_docteur="+num_doc.getText()+";");
                    
                    query1="DELETE FROM soigne WHERE no_malade="+mal.get(0)+" AND no_docteur="+doc.get(0)+";";
                    query2="DELETE FROM malade WHERE numero="+mal.get(0)+";";
                    executerSQLquery(query1,query2,"Champs supprimés");
                
                }else{//modif
                JOptionPane.showMessageDialog(null,"Ce malade ou ce docteur n'éxiste pas");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Maj_PH.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SupprimerActionPerformed
    /**
     * récupère les infos dans la table pour remplir les champs pour les mettre dans les champs de texte
     * @param evt click sur la JTable
     */
    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int i=table.getSelectedRow();
        TableModel model=table.getModel();
        idpat.setText(model.getValueAt(i,0).toString());
        nom.setText(model.getValueAt(i,1).toString());
        prenom.setText(model.getValueAt(i, 2).toString());
        adresse.setText(model.getValueAt(i, 3).toString());
        tel.setText(model.getValueAt(i,4).toString());
        mutuelle.setText(model.getValueAt(i,5).toString());
        num_doc.setText(model.getValueAt(i,6).toString());
        
        
    }//GEN-LAST:event_tableMouseClicked
    /**
     * vérification du bon fonctionnement d'une requête
     * @param query requête
     * @param message de confirmation ou d'erreur
     */
    public void executerSQLquery(String query,String message){
       Statement st;
       try{
           st=link.getConn().createStatement();
           if(st.executeUpdate(query)== 1)
           {
               DefaultTableModel model = (DefaultTableModel)table.getModel();
               model.setRowCount(0);
               AffichePatient();
               
               JOptionPane.showMessageDialog(null,message);
           }else{
               JOptionPane.showMessageDialog(null, message);
           }
       }catch(Exception ex){
           ex.printStackTrace();
       }
    }
    /**
     * vérifie le bon fonctionnement de deux requêtes
     * @param query1 requête 1
     * @param query2 requête 2
     * @param message message de confirmation ou d'erreur selon le déroulement
     */
    public void executerSQLquery(String query1,String query2,String message){
       Statement st;
       try{
           st=link.getConn().createStatement();
           if(st.executeUpdate(query1)== 1&&st.executeUpdate(query2)== 1)
           {
               DefaultTableModel model = (DefaultTableModel)table.getModel();
               model.setRowCount(0);
               AffichePatient();
               
               JOptionPane.showMessageDialog(null,message);
           }else{
               JOptionPane.showMessageDialog(null,message);
           }
       }catch(Exception ex){
           ex.printStackTrace();
       }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maj_PH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maj_PH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maj_PH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maj_PH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maj_PH(link).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajouter;
    private javax.swing.JButton Modifier;
    private javax.swing.JButton Retour;
    private javax.swing.JButton Supprimer;
    private javax.swing.JTextField adresse;
    private javax.swing.JTextField idpat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mutuelle;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField num_doc;
    private javax.swing.JTextField prenom;
    private javax.swing.JTable table;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables
}
